sonata_user:
    class:
        user: App\Application\Sonata\UserBundle\Entity\User
        group: App\Application\Sonata\UserBundle\Entity\Group
#    admin:
#        user:
#            class: App\Application\Sonata\UserBundle\Admin\UserAdmin
#        group:
#            class: App\Application\Sonata\UserBundle\Admin\GroupAdmin
